### ISSUE TITLE
Discrepancy in Matterport3D datset

### ISSUE THREAD

**Issue by krantiparida** [facebookresearch/sound-spaces#12]
Hi, 
I noticed some discrepancies with the matterport dataset.
1. In the original matterport dataset, there are 90 scenes but only 85 scenes are considered. Is there any specific reason for that? 
2. The sampling rate for Replica is 44.1 kHz whereas matterport is 16 kHz. could you please let me know why there is a difference in sampling rate?
3. Finally in the partial binaural RIRs (867G) provided by you contains only the data for 83 scenes instead of 85.

Thanks for your time.

**Comment by ChanganVR** [comment]
Hi Kranti, 

1. This is because we had some audio rendering issues with the other 5 scenes so we didn't use them in the end.

2. It's only because the data size for matterport would be too big if we use 44.1 kHz for it.  And usually 16kHz is enough for processing the sound.

3. That's because after filtering (mininum distance to goal greater than 4, geodesic distance / euclidean distance > 1.1, mininum 10 nodes in the navigability graph), these two environments have no nodes left. But if you want to use these environments, the data is available in the full binaural RIR zip file.

**Comment by krantiparida** [comment]
Thanks for the clarification.
