### ISSUE TITLE
How to add an agent to this environment to realize a multi-agent environment?

### ISSUE THREAD

**Issue by yyf17** [facebookresearch/sound-spaces#16]
How to add an agent to this environment to realize a multi-agent environment?

**Comment by ChanganVR** [comment]
I haven't experimented with this feature. But it should be straight forward to implement by adding the starting rotation/position of another agent in the episode configuration, update the action space to include another agent's action, calculate positions for two in the sim.step() function. I think this is doable in SoundSpaces since observations are rendered offline and you can calculate positions by yourself. Habitat simulator doesn't seem to support this features now.

**Comment by yyf17** [comment]
ok,thanks.I will have a try under your guidance.
