### ISSUE TITLE
The Validation didn't run all of the 500 episodes.

### ISSUE THREAD

**Issue by JeremyLinky** [facebookresearch/sound-spaces#22]
Hi, Changan,  I'm facing a problem that when I evaluate my trained models, the validation always didn't run all of the 500 episodes. Just like   5%|██                                        | 25/500 [00:18<05:18,  1.49it/s]   and it will be stoped from evaluating.  I have checked the validation jason which includes 4 scenes and 501 episodes. So what is the problem? Thanks a lot!

**Comment by ChanganVR** [comment]
Did you do any modification to the code? I haven't encoutered the case. 

Basically evaluation exits when it detects a duplicated episode id, and to debug this, you can print each episode to locate which episode is repeated. But it's hard for me to say what's wrong without knowing what you have modified.

**Comment by PeihaoChen** [comment]
@JeremyLinky Hi, Jeremy. I also encounter this problem. When I set NUM_PROCESSES to 1, it can evaluate all 500 episodes normally. Otherwise, it will stop after running a certain number of episodes.  

You can try to set NUM_PROCESSES to 1 and check whether everything is ok. Also, looking forward to a response from Changan.

**Comment by ChanganVR** [comment]
@JeremyLinky @PeihaoChen I just remembered that I put all episode configurations in one json file (e.g. test_telephone.json.gz). And this code loads one json file per process. If you assign more than two processes, then they load the same episodes and that's why it would quite early. 

I don't know if you have some specific need for assigning more than 1 processes, if you do, you can manually split the json file into multiple files and run the same number of processes to read them sequentially.

**Comment by PeihaoChen** [comment]
Thanks for your kind reply! Best.
