### ISSUE TITLE
Discrepancy in episode data of Matterport3D

### ISSUE THREAD

**Issue by Abundant-me** [facebookresearch/sound-spaces#36]
Hi Changan.
I notice some discrepancies with the episode data of matterport.

The number of scenes of matterport is 85 in paper. And I have known that there are 83 instead of 85 scenes from issue #12. But I count the number of scenes in all episode data, and find that there are only 81, 59/10/11 for train/val/test, respectively. Do I miss something?

Here are the scenes of val and test that I count.

val: 'QUCTc6BB5sX', 'EU6Fwq7SyZv', '2azQ1b91cZZ', 'Z6MFQCViBuw', 'pLe4wQe7qrG', 'oLBMNvg9in8', 'X7HyMhZNoso', 'zsNo4HB9uLZ', 'TbHJrupSAjP', '8194nk5LbLH'

test: 'pa4otMbVnkk', 'yqstnuAEVhm', '5ZKStnWn8Zo', 'Vt2qJdWjCF2', 'wc2JMjhGNzB', 'fzynW3qQPVF', 'UwV83HsGsw3', 'q9vSo1VnCiC', 'ARNzJeq3xxb', 'gYvKGZ5eRqb', 'jtcxE69GiFV', 'gxdoqLR6rwA'

Thank you for your time.

**Comment by czha5168** [comment]
Hi Dongyu, I guess your question could be answered from here: https://github.com/facebookresearch/sound-spaces/issues/12.

Hi Changan, I wonder **which file types are unnecessary for using scripts/cache_observations.py to collect observations for MP3D dataset**. The entire Matterport3D release (1.3TB) is big and I have spent more than 1 week to download only about 250GB. So I am thinking about removing the unnecessary downloading tasks... All file types are listed below and thanks for your time!
![Screenshot from 2021-01-15 23-02-35](https://user-images.githubusercontent.com/40653168/104725152-c6a68200-5785-11eb-8963-1b43552a9b20.png)

**Comment by ChanganVR** [comment]
Hi @Abundant-me, 5 scenes were not used among the 90 scens due to audio rendering issues and the rest scenes are missing due to filtering (the ratio of euclidean distance to geodesic distance greater than 1.1 and min distance greater than 2m) or sampling (we sample the 500 validation episodes and 1000 test episodes from val and test scenes proportional to the number of episodes in each scene and thus some scenes might have zero sampled they are small). That's why we claim we used 85 scenes in the paper, although some scenes are being suppressed in the data processing stage.

**Comment by Abundant-me** [comment]
Thanks for your reply.
