### ISSUE TITLE
How to use multiple GPUs to train SAVi?

### ISSUE THREAD

**Issue by gtatiya** [facebookresearch/sound-spaces#61]
I am training savi on a machine that has 3 GPUs, but only one GPU is being used. I also tried running the slurm.sh file on a cluster that has multiple GPUs, but still only one GPU was used. Could you please help me figure out how to use multiple GPUs?

**Comment by ChanganVR** [comment]
Slurm.sh works on a cluster that has a slurm setup. If it's a single machine, probably it doesn't work. While I don't have much experience with that, @yyf17 seems to have made that work. He should have some idea on how to do that.

**Comment by yyf17** [comment]
I did it by modifying the configuration file of ddpo. The specific implementation is as follows:
If you want to use 4 GPU cards, change the world_size to 4 in the file((https://github.com/facebookresearch/sound-spaces/blob/f11fef81db0c6b05d42fd062faa4929195de4ddf/ss_baselines/savi/ddppo/algo/ddp_utils.py#L165).
I hope my method can help you.
Good luck!

**Comment by yyf17** [comment]
@gtatiya 
Sorry. Maybe I forgot some details about what I do.
You may do two extra things:
1) add three line code
before the line [here](https://github.com/facebookresearch/sound-spaces/blob/f11fef81db0c6b05d42fd062faa4929195de4ddf/ss_baselines/savi/ddppo/algo/ddp_utils.py#L151) 
add
```
   os.environ["LOCAL_RANK"] = 0
    os.environ["RANK"] = 0
    os.environ["WORLD_SIZE"] = 3
```
2) run code with the following style:
```
python ss_baselines/savi/run.py --exp-config ss_baselines/savi/config/semantic_audionav/savi_pretraining.yaml --model-dir data/models/savi
python ss_baselines/savi/run.py --exp-config ss_baselines/savi/config/semantic_audionav/savi.yaml --model-dir data/models/savi
```
I hope this will help you.
Good luck!

**Comment by gtatiya** [comment]
@yyf17 

Thank you. I added those 3 lines and ran the code.

First, I got this error: 
```
Traceback (most recent call last):
  File "ss_baselines/savi/run.py", line 153, in <module>
    main()
  File "ss_baselines/savi/run.py", line 116, in main
    trainer.train()
  File "/nas/home/i21_gtatiya/shadyside/projects/1_my/sound-spaces/ss_baselines/savi/ddppo/algo/ddppo_trainer.py", line 232, in train
    self.local_rank, tcp_store = init_distrib_slurm(self.config.RL.DDPPO.distrib_backend)
  File "/nas/home/i21_gtatiya/shadyside/projects/1_my/sound-spaces/ss_baselines/savi/ddppo/algo/ddp_utils.py", line 151, in init_distrib_slurm
    os.environ["LOCAL_RANK"] = 0
  File "/home/i21_gtatiya/miniconda3/envs/savi/lib/python3.6/os.py", line 674, in __setitem__
    value = self.encodevalue(value)
  File "/home/i21_gtatiya/miniconda3/envs/savi/lib/python3.6/os.py", line 744, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not int
```

So, I converted int to str:
```
os.environ["LOCAL_RANK"] = "0"
os.environ["RANK"] = "0"
os.environ["WORLD_SIZE"] = "3"
```

On a single machine with 3 GPUs, the code still gets stuck.

On a cluster with 2 GPUs, I got this error:
```
Traceback (most recent call last):
  File "/cluster/tufts/sinapovlab/gtatiy01/condaenv/savi/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/cluster/tufts/sinapovlab/gtatiy01/condaenv/savi/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/cluster/home/gtatiy01/projects/sound-spaces/ss_baselines/savi/run.py", line 144, in <module>
    main()
  File "/cluster/home/gtatiy01/projects/sound-spaces/ss_baselines/savi/run.py", line 107, in main
    trainer.train()
  File "/cluster/home/gtatiy01/projects/sound-spaces/ss_baselines/savi/ddppo/algo/ddppo_trainer.py", line 232, in train
    self.config.RL.DDPPO.distrib_backend
  File "/cluster/home/gtatiy01/projects/sound-spaces/ss_baselines/savi/ddppo/algo/ddp_utils.py", line 174, in init_distrib_slurm
    master_addr, master_port, world_size, world_rank == 0
RuntimeError: Address already in use
srun: error: cc1gpu002: task 0: Exited with exit code 1
```

Could you please help?

**Comment by gtatiya** [comment]
@yyf17 @ChanganVR 
Thank you for helping.

I requested 2 GPUs on a different node in which I am not running any process. The code was stuck for for 35 min, and then I got this error:
```
+ srun python -u -m ss_baselines.savi.run --exp-config ss_baselines/savi/config/semantic_audionav/savi_pretraining.yaml --model-dir data/models/savi_2gpu
2021-10-15 11:07:20,481 2 GPU usage: [0.0, 0.0]
Traceback (most recent call last):
  File "/cluster/tufts/sinapovlab/gtatiy01/condaenv/saven/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/cluster/tufts/sinapovlab/gtatiy01/condaenv/saven/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/cluster/home/gtatiy01/projects/sound-spaces/ss_baselines/savi/run.py", line 144, in <module>
    main()
  File "/cluster/home/gtatiy01/projects/sound-spaces/ss_baselines/savi/run.py", line 107, in main
    trainer.train()
  File "/cluster/home/gtatiy01/projects/sound-spaces/ss_baselines/savi/ddppo/algo/ddppo_trainer.py", line 232, in train
    self.config.RL.DDPPO.distrib_backend
  File "/cluster/home/gtatiy01/projects/sound-spaces/ss_baselines/savi/ddppo/algo/ddp_utils.py", line 177, in init_distrib_slurm
    backend, store=tcp_store, rank=world_rank, world_size=world_size
  File "/cluster/tufts/sinapovlab/gtatiy01/condaenv/saven/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 433, in init_process_group
    timeout=timeout)
  File "/cluster/tufts/sinapovlab/gtatiy01/condaenv/saven/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 508, in _new_process_group_helper
    timeout=timeout)
RuntimeError: Socket Timeout
srun: error: cc1gpu005: task 0: Exited with exit code 1

```

Running on single GPU is very slow, could you please help?

**Comment by luca-bondi** [comment]
Hi @gtatiya,

I came across your same question and timeout issue. The piece I was missing is that to use multiple GPUs on the same workstations, I have to manually start one training process per GPU. The following example is for a workstation with 3 GPUs and direct shell access, but I believe a similar approach will [work with slurm too](https://github.com/facebookresearch/sound-spaces/blob/f11fef81db0c6b05d42fd062faa4929195de4ddf/ss_baselines/savi/ddppo/algo/ddp_utils.py#L157), by setting different env variables.

Shell 1 (primary process, will use GPU 0):
```bash
WORLD_SIZE=3; LOCAL_RANK=0; RANK=0; python -m ss_baselines.savi.run --exp-config ...
```

Shell 2 (secondary process, will use GPU 1):
```bash
WORLD_SIZE=3; LOCAL_RANK=1; RANK=1; python -m ss_baselines.savi.run --exp-config ...
```

Shell 3 (secondary process, will use GPU 2):
```bash
WORLD_SIZE=3; LOCAL_RANK=2; RANK=2; python -m ss_baselines.savi.run --exp-config ...
```

The order in which you start the processes doesn't really matter, once they are all there they'll start working. 

One thing you may want to change is adding `map_location='cpu'` to this [torch.load](https://github.com/facebookresearch/sound-spaces/blob/f11fef81db0c6b05d42fd062faa4929195de4ddf/ss_baselines/savi/models/belief_predictor.py#L97), so that your pre-trained weights are not sitting in GPU 0 for each of the processes, wasting precious memory.

Hope this helps!

**Comment by ChanganVR** [comment]
This script might also be helpful for running multi-gpu training on single node: https://github.com/facebookresearch/habitat-lab/tree/main/habitat_baselines/rl/ddppo

**Comment by gtatiya** [comment]
Hi @luca-bondi, thank you for posting the commands. I tried it with a workstation with 4 GPUs and it works perfectly. I just had to add `export` before variables (e.g., `export WORLD_SIZE=3`).

**Comment by swapb94** [comment]
Hi, I have a single node with 2 GPUs.
I followed the steps given by @luca-bondi and @gtatiya above. Particularly, I ran the below two commands in two separate terminals.

> export WORLD_SIZE=2; export LOCAL_RANK=0; export RANK=0; python ss_baselines/savi/run.py --exp-config ss_baselines/savi/config/semantic_audionav/savi.yaml --model-dir data/models/savi_finetune

and 

> export WORLD_SIZE=2; export LOCAL_RANK=1; export RANK=1; python ss_baselines/savi/run.py --exp-config ss_baselines/savi/config/semantic_audionav/savi.yaml --model-dir data/models/savi_finetune

The script  is now running on two GPUs as can be seen below,
![gsf](https://github.com/user-attachments/assets/11e6475d-ba45-46a0-a85d-cecdb564b7c9)

However, I am confused because there isn't any speedup happening, for instance, from the log, it can be seen the consecutive updates (intervals of 10) still take 1.5~2 mins, which is same when I was running on a single node with GPU.
![vz](https://github.com/user-attachments/assets/f60975f2-3d90-4055-a753-e32a115a731b)


1. Am I missing something? 

2. Also, the log is generated only on the first terminal, the second terminal shows no output after,
`INFO:root:AudioNavSMTNet ===> Freezing goal, visual, fusion encoders!`
`INFO:root:Loaded pretrained label classifier`
`INFO:root:Freezing belief predictor weights`
which I believe is as expected, right?


I even tried the suggestion by @ChanganVR, 

> This script might also be helpful for running multi-gpu training on single node: https://github.com/facebookresearch/habitat-lab/tree/main/habitat_baselines/rl/ddppo

but the same pattern is observed ... time between every 10 updates is still 1.5~2 mins.
