### ISSUE TITLE
Issues downloading full binaural RIRs for mp3d/1pXnuDYAj8r.tar.gz

### ISSUE THREAD

**Issue by auroracramer** [facebookresearch/sound-spaces#70]
Hello,

First of all thanks for all of the work you've put into this framework and research! :)

I'm trying to download the full binaural RIRs, and it seems that I'm having an issue with `binaural_rirs/mp3d/1pXnuDYAj8r.tar.gz` (downloaded from http://dl.fbaipublicfiles.com/SoundSpaces/binaural_rirs/mp3d/1pXnuDYAj8r.tar.gz, which I got from [the download script](https://github.com/facebookresearch/sound-spaces/blob/main/scripts/download_data.py#L33)). It appears that the file I've downloaded isn't a valid .tar.gz file:

```
 $ tar xf 1pXnuDYAj8r.tar.gz 

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
 $ file 1pXnuDYAj8r.tar.gz 
1pXnuDYAj8r.tar.gz: data
 $ file --mime-type 1pXnuDYAj8r.tar.gz 
1pXnuDYAj8r.tar.gz: application/octet-stream
```

I've tried downloading it using `wget`, `curl`, and Firefox but they result in the same thing. I've checked some of the other RIR tar.gz's and they seem to be valid (tested with `gzip -t -v`), it just seems to be 1pXnuDYAj8r for me. Do you know what I need to change or do to get the correct file?

Thanks!

**Comment by ChanganVR** [comment]
Hi @auroracramer, I downloaded the file and it was broken for me as well. The good news here is that the full binaural rirs I currently have on AWS S3 are actually the same as the partially binaural rirs because I uploaded the wrong folders. So if you have already downloaded the partitial RIRs, then you already have the rirs for 1pXnuDYAj8r. I haven't fixed it because no one has really requested the full dataset of binaural RIRs so far. The bad news is the true full binaural RIRs are 5.4T for Matterport and 357G for Replica. If you need the full set of RIRs, I can definitely upload them to AWS and fix the links. It might take a couple days though. Let me know!

**Comment by auroracramer** [comment]
Hi @ChanganVR, thanks for checking and for clarifying! This is all super helpful to know. I don't have any particular need for the full binaural RIRs at this moment, I was just trying to get ahold of all of the available data for completeness. Thanks for your willingness to help though!
